# model
model_name_or_path: liswei/OpenELM-270M-zh-base
# method
stage: pt
do_train: true
finetuning_type: full
use_galore: true
galore_layerwise: false
galore_target: token_embeddings,qkv_proj,proj_2,out_proj,proj_1
galore_rank: 1024
galore_scale: 4.0
galore_update_interval: 200
pure_bf16: true

# dataset
dataset: zhtw-news-and-articles-2B
cutoff_len: 2048
preprocessing_num_workers: 8

# output
output_dir: saves/OpenELM-270M/zh-cp-galore
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all

# train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 1000

do_eval: false