# model
model_name_or_path: saves/OpenELM-270M/zh-cp-ablation-galore
# method
stage: sft
do_train: true
finetuning_type: full
use_galore: true
galore_layerwise: false
galore_target: all
galore_rank: 1024
galore_scale: 4.0
galore_update_interval: 200
pure_bf16: false

# dataset
dataset: en2tw-alignment-sft,TaiwanChat
template: llama2
cutoff_len: 1024
val_size: 0.1
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-270M/zh-sft-ablation-galore
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all

# train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 1000
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 500
