# model
model_name_or_path: liswei/OpenELM-1_1B-zh-base
# method
stage: pt
do_train: true
finetuning_type: full
use_galore: true
galore_layerwise: false
galore_target: all
galore_rank: 1024
galore_scale: 0.5
galore_update_interval: 200
pure_bf16: true

# dataset
dataset: zhtw-news-and-articles-2B
cutoff_len: 1024
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-1_1B/zh-cp-galore
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all

# train
per_device_train_batch_size: 16
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 1000

do_eval: false