# model
model_name_or_path: saves/OpenELM-270M/zh-base
# method
stage: pt
do_train: true
finetuning_type: full
use_galore: true
galore_layerwise: false
galore_target: token_embeddings,qkv_proj,proj_2,out_proj,proj_1
galore_rank: 512
galore_scale: 4.0
galore_update_interval: 500

# dataset
dataset: zhtw-news-and-articles-2B
cutoff_len: 1024
val_size: 0.05
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-270M/zh-cp-galore
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all

# train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 1500
packing: true

# eval
per_device_eval_batch_size: 6
evaluation_strategy: steps
eval_steps: 1500
