# model
model_name_or_path: liswei/OpenELM-1_1B-zh-base
# method
stage: pt
do_train: true
finetuning_type: full
fp16: true

# dataset
dataset: zhtw-news-and-articles-2B
cutoff_len: 2048
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-1_1B/OpenELM-1_1B-zh-cp-8GPU
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all
push_to_hub: true

# train
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1

do_eval: false