# model
model_name_or_path: saves/OpenELM-270M/zh-base
# method
stage: pt
do_train: true
finetuning_type: full
use_badam: true
badam_switch_mode: random
badam_switch_interval: 50
badam_verbose: 2

# dataset
dataset: bigscience-wiki-zhtw
template: llama2
cutoff_len: 1024
val_size: 0.05
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-270M/zh-cp-ablation
logging_steps: 10
save_steps: 12000
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

# train
per_device_train_batch_size: 14
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 500
push_to_hub: true

# evalw
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 4000
