# model
model_name_or_path: liswei/OpenELM-270M-zh-base
# method
stage: pt
do_train: true
finetuning_type: full
pure_bf16: false

# dataset
dataset: zhtw-news-and-articles-2B
cutoff_len: 1024
preprocessing_num_workers: 16

# output
output_dir: saves/OpenELM-270M/zh-cp
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true
report_to: all
push_to_hub: true

# train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 1000
packing: true

do_eval: false